name               = "spam-scorer-ai"
main               = "worker.js"
compatibility_date = "2024-09-23"
account_id         = "8edbb93852e6e7a4f23bb0cf7069516a"

[[d1_databases]]
binding         = "DB"
database_name   = "outlook-spam-scorer-db"
database_id     = "2624fbf4-aaa2-44f6-afdf-e489fe4a3dc9"
