"""Englische Übersetzung der Formular-Schemata und der Oberfläche.

Schlüssel sind die deutschen Strings aus formulare.py. Fehlt ein Eintrag, meldet build.py ihn.
Auswahlwerte werden dem Server weiterhin auf Deutsch gesendet (value=deutsch, angezeigt englisch).
"""
T = {
# Gruppen, Titel, Leads
"Immobilien": "Property",
"Kaufvertrag Haus oder Grundstück": "Purchase Agreement: House or Land",
"Für den Entwurf eines Kaufvertrags über ein Haus, ein Grundstück oder eine Wohnung. Ausfüllen kann der Verkäufer, der Käufer oder der Makler.": "For drafting a purchase agreement for a house, plot of land or apartment. Can be completed by the seller, the buyer or the estate agent.",
"Kaufvertrag Eigentumswohnung": "Purchase Agreement: Condominium",
"Für den Kauf oder Verkauf einer Eigentumswohnung. Zusätzlich zum Haus-Fragebogen werden Angaben zur Gemeinschaft und zum Verwalter gebraucht.": "For buying or selling a condominium apartment. In addition to the house questionnaire, details of the owners' association and the property manager are needed.",
"Grundschuldbestellung": "Land Charge (Mortgage) Registration",
"Für die Bestellung einer Grundschuld zugunsten einer Bank, etwa zur Finanzierung eines Kaufs oder Umbaus. Das Grundschuldformular der Bank bitte zum Termin mitbringen.": "For registering a land charge (Grundschuld) in favour of a bank, for example to finance a purchase or renovation. Please bring the bank's land charge form to the appointment.",
"Übergabe und Schenkung": "Transfer and Gift of Property",
"Für die Übertragung eines Hauses, einer Wohnung oder eines Grundstücks zu Lebzeiten, meist an Kinder. Mit Wohnrecht, Nießbrauch, Pflege und Rückforderungsrechten.": "For transferring a house, apartment or plot of land during your lifetime, usually to children. With right of residence, usufruct, care obligations and reclaim rights.",
"Erben und Vererben": "Wills and Inheritance",
"Testament und Erbvertrag": "Will and Inheritance Contract",
"Für den Entwurf eines Einzeltestaments, eines gemeinschaftlichen Testaments von Ehegatten oder eines Erbvertrags.": "For drafting an individual will, a joint will of spouses or an inheritance contract.",
"Erbschein und Erbausschlagung": "Certificate of Inheritance and Disclaimer",
"Nach einem Todesfall: Antrag auf Erbschein, Erbausschlagung oder Auseinandersetzung unter Erben.": "After a death: application for a certificate of inheritance, disclaimer of an inheritance, or distribution of the estate among heirs.",
"Vorsorge": "Powers of Attorney",
"Vorsorgevollmacht und Patientenverfügung": "Lasting Power of Attorney and Living Will",
"Für den Entwurf von Vorsorgevollmacht, Patientenverfügung und Betreuungsverfügung. Für Ehegatten bitte je einen Bogen.": "For drafting a lasting power of attorney, a living will and a guardianship directive. Spouses please complete one form each.",
"Familie": "Family",
"Ehevertrag": "Marriage Contract",
"Vor oder während der Ehe: Güterstand, Unterhalt, Versorgungsausgleich, Schutz eines Betriebs.": "Before or during marriage: matrimonial property regime, maintenance, pension rights adjustment, protection of a business.",
"Scheidungsfolgenvereinbarung": "Divorce Settlement Agreement",
"Bei Trennung und Scheidung: Vermögen, Wohnung, Unterhalt, Versorgungsausgleich und Kinder einvernehmlich regeln.": "On separation and divorce: settle assets, the home, maintenance, pension rights and arrangements for children by agreement.",
"Unternehmen": "Business",
"GmbH- oder UG-Gründung": "Formation of a GmbH or UG",
"Für Gesellschaftsvertrag oder Musterprotokoll, Gesellschafterliste und Handelsregisteranmeldung. Gilt auch für die Unternehmergesellschaft (haftungsbeschränkt).": "For the articles of association or model protocol, list of shareholders and commercial register filing. Also applies to the UG (haftungsbeschränkt), the German mini-GmbH.",
"Übertragung von Geschäftsanteilen": "Transfer of GmbH Shares",
"Verkauf oder Schenkung von GmbH-Anteilen, auch Eintritt oder Ausscheiden eines Gesellschafters.": "Sale or gift of GmbH shares, including a shareholder joining or leaving.",
"Handelsregisteranmeldung": "Commercial Register Filing",
"Änderungen bei GmbH, UG, Einzelkaufleuten und Personengesellschaften: Geschäftsführerwechsel, Sitzverlegung, Satzungsänderung, Prokura, Liquidation.": "Changes for GmbH, UG, sole traders and partnerships: change of managing director, relocation of seat, amendment of articles, commercial power of attorney (Prokura), liquidation.",
"Vereinsgründung und Vereinsregister": "Association Formation and Register",
"Anmeldung eines neuen Vereins oder Änderung von Vorstand und Satzung beim Vereinsregister.": "Registration of a new association (Verein) or changes to its board and statutes in the register of associations.",
"Beglaubigungen": "Certifications",
"Beglaubigung": "Certification",
"Unterschriftsbeglaubigung oder beglaubigte Abschrift. Kurzer Vorgang, meist ohne langen Termin.": "Certification of a signature or a certified copy. A short procedure, usually without a long appointment.",
# Personen
"Verkäufer": "Seller",
"Bei mehreren Eigentümern bitte alle nennen, weitere unter Besonderheiten.": "If there are several owners, please name all of them; additional ones under Remarks.",
"Vor- und Nachname": "First and last name",
"Geburtsdatum": "Date of birth",
"Anschrift": "Address",
"Telefon": "Telephone",
"E-Mail": "Email",
"Steuer-Identifikationsnummer": "German tax identification number",
"11 Ziffern, steht auf dem Einkommensteuerbescheid": "11 digits, shown on the income tax assessment; leave blank if you have none",
"Familienstand": "Marital status",
"ledig": "single", "verheiratet": "married", "geschieden": "divorced", "verwitwet": "widowed", "eingetragene Lebenspartnerschaft": "registered civil partnership",
"Käufer": "Buyer",
"Bei Erwerb zu mehreren: alle Käufer und das gewünschte Verhältnis, etwa je zur Hälfte.": "If buying jointly: all buyers and the intended shares, for example one half each.",
"Erwerbsverhältnis bei mehreren Käufern": "Shares if there are several buyers",
"z. B. je 1/2": "e.g. 1/2 each",
"Objekt": "Property",
"Anschrift des Objekts": "Address of the property",
"Art": "Type",
"Einfamilienhaus": "Detached house", "Doppelhaushälfte, Reihenhaus": "Semi-detached or terraced house", "Eigentumswohnung": "Condominium apartment", "Mehrfamilienhaus": "Apartment building", "Unbebautes Grundstück": "Undeveloped land", "Gewerbe": "Commercial", "Landwirtschaft": "Agricultural",
"Grundbuch von, Blatt, Flurstück": "Land register (Grundbuch) district, sheet, parcel",
"falls bekannt": "if known",
"Eingetragene Belastungen": "Registered encumbrances",
"Grundschulden, Wohnrechte, Wegerechte; falls bekannt": "land charges, rights of residence, rights of way; if known",
"Nutzung und Inventar": "Use and contents",
"Vermietet?": "Let to tenants?",
"Nein": "No", "Ja, Mietvertrag geht über": "Yes, the tenancy passes to the buyer", "Ja, wird vor Übergabe beendet": "Yes, but ends before handover",
"Mitverkauftes Inventar": "Contents included in the sale",
"Küche, Möbel, Wert": "kitchen, furniture, value",
"Bekannte Mängel": "Known defects",
"Der Verkäufer muss bekannte Mängel offenlegen.": "The seller must disclose known defects.",
"Kaufpreis und Zahlung": "Purchase price and payment",
"Kaufpreis in Euro": "Purchase price in euros",
"Davon für Inventar in Euro": "Of which for contents, in euros",
"Finanzierung": "Financing",
"Eigenmittel": "Own funds", "Bankdarlehen, Grundschuld nötig": "Bank loan, land charge required", "Teils, teils": "Partly both",
"Bank und Höhe der Grundschuld": "Bank and amount of the land charge",
"Gewünschte Übergabe": "Desired handover date",
"Makler": "Estate agent",
"Name, oder: keiner": "name, or: none",
"Rückfragen": "Contact for queries",
"Ansprechperson": "Contact person",
"Erreichbar": "Best time to call",
"z. B. vormittags": "e.g. mornings",
"Besonderheiten, Wünsche, Fragen": "Remarks, wishes, questions",
# Wohnung
"Wohnung": "Apartment",
"Anschrift, Lage im Haus": "Address, location in the building",
"Wohnungs-Nummer laut Teilungserklärung": "Apartment number per declaration of division",
"Miteigentumsanteil": "Co-ownership share",
"z. B. 125/1000": "e.g. 125/1000",
"Stellplatz, Garage, Keller": "Parking space, garage, cellar",
"mit Nummern, falls Sondereigentum oder Sondernutzungsrecht": "with numbers, if separate ownership or special right of use",
"Verwalter mit Anschrift": "Property manager with address",
"Monatliches Hausgeld in Euro": "Monthly service charge in euros",
"Stand der Erhaltungsrücklage in Euro": "Maintenance reserve balance in euros",
"Beschlossene Sonderumlagen oder Sanierungen": "Resolved special levies or renovations",
# Grundschuld
"Eigentümer": "Owner",
"Alle im Grundbuch eingetragenen Eigentümer.": "All owners registered in the land register.",
"Grundschuld": "Land charge",
"Bank mit Anschrift": "Bank with address",
"Grundschuldbetrag in Euro": "Land charge amount in euros",
"Grundschuldzins in Prozent": "Land charge interest in percent",
"steht im Bankformular, meist 12 bis 18": "shown on the bank form, usually 12 to 18",
"Anlass": "Purpose",
"Kauf": "Purchase", "Neubau": "New build", "Umbau, Sanierung": "Conversion, renovation", "Umschuldung": "Refinancing", "Sonstiges": "Other",
"Ansprechperson bei der Bank": "Contact at the bank",
"Gewünschter Termin bis": "Desired appointment by",
# Übergabe
"Übergeber": "Transferor",
"Alle Eigentümer.": "All owners.",
"Übernehmer": "Transferee",
"Bei mehreren: alle und das Verhältnis.": "If several: all of them and their shares.",
"Verwandtschaft zum Übergeber": "Relationship to the transferor",
"Kind": "Child", "Enkel": "Grandchild", "Ehegatte": "Spouse", "Sonstige": "Other",
"Absicherung des Übergebers": "Protection of the transferor",
"Wohnrecht oder Nießbrauch": "Right of residence or usufruct",
"Wohnrecht an bestimmten Räumen": "Right of residence in specific rooms", "Nießbrauch am ganzen Objekt": "Usufruct of the whole property", "Keines": "None",
"Räume für das Wohnrecht": "Rooms covered by the right of residence",
"z. B. Erdgeschoss": "e.g. ground floor",
"Pflegeverpflichtung des Übernehmers": "Care obligation of the transferee",
"Ja": "Yes", "Bitte erklären": "Please explain",
"Zahlung an den Übergeber": "Payment to the transferor",
"einmalig oder monatlich, Betrag": "one-off or monthly, amount",
"Rückforderungsrechte": "Reclaim rights",
"Übliche (Verkauf, Insolvenz, Scheidung, Vorversterben)": "Usual ones (sale, insolvency, divorce, transferee dying first)", "Keine": "None",
"Ungefährer Wert des Objekts in Euro": "Approximate value of the property in euros",
"Geschwister und Ausgleich": "Siblings and compensation",
"Weitere Kinder des Übergebers": "Other children of the transferor",
"Namen": "names",
"Ausgleich": "Compensation",
"Abfindung in Geld": "Cash settlement", "Pflichtteilsverzicht": "Waiver of compulsory portion", "Anrechnung auf Erbteil": "Set-off against inheritance", "Kein Ausgleich": "No compensation",
"Abfindungsbetrag in Euro": "Settlement amount in euros",
# Testament
"Erblasser": "Testator",
"Ehegatte oder zweiter Erblasser": "Spouse or second testator",
"Nur bei gemeinschaftlichem Testament oder Erbvertrag.": "Only for a joint will or inheritance contract.",
"Kinder mit Geburtsdatum": "Children with dates of birth",
"auch aus früheren Beziehungen": "including from previous relationships",
"Ehevertrag vorhanden?": "Is there a marriage contract?",
"Ja, Gütertrennung": "Yes, separation of property", "Ja, modifizierte Zugewinngemeinschaft": "Yes, modified community of accrued gains", "Ja, sonstiges": "Yes, other",
"Frühere Testamente oder Erbverträge": "Earlier wills or inheritance contracts",
"Ja, sollen aufgehoben werden": "Yes, to be revoked", "Ja, sollen bestehen bleiben": "Yes, to remain in force",
"Vermögen": "Assets",
"Ungefähre Angaben genügen. Sie bestimmen den Geschäftswert und die Beratung zu Pflichtteil und Steuer.": "Approximate figures are sufficient. They determine the transaction value and the advice on compulsory portions and tax.",
"Anschrift, ungefährer Wert, Eigentümer": "address, approximate value, owner",
"Bankguthaben, Wertpapiere in Euro": "Bank balances, securities in euros",
"Unternehmen, Beteiligungen": "Businesses, shareholdings",
"Verbindlichkeiten in Euro": "Liabilities in euros",
"Vermögen im Ausland": "Assets abroad",
"Land, Art": "country, type",
"Wünsche": "Wishes",
"Wer soll erben, in welchem Verhältnis?": "Who should inherit, and in what shares?",
"Bei Ehegatten: Wer erbt nach dem Tod des Längerlebenden?": "For spouses: who inherits after the death of the survivor?",
"Vermächtnisse": "Legacies",
"einzelne Gegenstände oder Beträge an bestimmte Personen": "specific items or sums to specific persons",
"Testamentsvollstreckung gewünscht?": "Executor wanted?",
"Testamentsvollstrecker": "Executor",
"Ersatzerben, falls ein Erbe vorverstirbt": "Substitute heirs if an heir dies first",
# Erbschein
"Anliegen": "Request",
"Was wird gebraucht?": "What is needed?",
"Erbschein": "Certificate of inheritance", "Erbausschlagung": "Disclaimer of inheritance", "Erbauseinandersetzung": "Distribution of the estate", "Europäisches Nachlasszeugnis": "European Certificate of Succession", "Weiß ich nicht": "I don't know",
"Verstorbene Person": "Deceased person",
"Name": "Name",
"Sterbedatum": "Date of death",
"Letzter Wohnsitz": "Last residence",
"Familienstand beim Tod": "Marital status at death",
"Testament oder Erbvertrag vorhanden?": "Is there a will or inheritance contract?",
"Ja, notariell": "Yes, notarial", "Ja, handschriftlich": "Yes, handwritten", "Unbekannt": "Unknown",
"Staatsangehörigkeit, Vermögen im Ausland": "Nationality, assets abroad",
"Antragsteller": "Applicant",
"Die Person, die den Antrag stellt oder ausschlägt.": "The person applying or disclaiming.",
"Angehörige und Nachlass": "Relatives and estate",
"Ehegatte, Kinder, ggf. Eltern und Geschwister des Verstorbenen": "Spouse, children and, if applicable, parents and siblings of the deceased",
"Name, Geburtsdatum, Anschrift; auch vorverstorbene Kinder mit deren Kindern": "name, date of birth, address; including predeceased children and their children",
"Ungefährer Nachlasswert in Euro": "Approximate value of the estate in euros",
"Immobilien im Nachlass": "Real estate in the estate",
"Bei Ausschlagung: Grund": "If disclaiming: reason",
"z. B. Überschuldung": "e.g. over-indebtedness",
# Vollmacht
"Vollmachtgeber": "Grantor (the person giving the power)",
"Bevollmächtigte Person 1": "Attorney 1 (person authorised)",
"Bevollmächtigte Person 2": "Attorney 2",
"Ersatz oder gemeinsam.": "As substitute or jointly.",
"Ausgestaltung": "Arrangement",
"Handeln die Bevollmächtigten": "The attorneys act",
"Jeder allein": "Each alone", "Nur gemeinsam": "Only jointly", "Person 2 nur, wenn Person 1 verhindert": "Person 2 only if person 1 is unavailable",
"Gilt die Vollmacht": "The power takes effect",
"Sofort, mit interner Absprache": "Immediately, with an internal agreement",
"Vermögen, Bank, Verträge": "Assets, banking, contracts", "Immobilien, Grundbuch": "Real estate, land register", "Gesundheit, Ärzte, Pflege": "Health, doctors, care", "Aufenthalt, Heim, Wohnung": "Residence, care home, housing", "Post, Behörden, Gerichte": "Post, authorities, courts", "Digitales, Konten im Internet": "Digital matters, online accounts",
"Patientenverfügung": "Living will",
"Ja, mit beurkunden": "Yes, notarise as well", "Liegt bereits vor": "Already exists",
"Betreuungsverfügung": "Guardianship directive",
"Ja, gleiche Personen": "Yes, same persons", "Ja, andere Person": "Yes, another person",
"Eintragung im Zentralen Vorsorgeregister gewünscht": "Register with the Central Register of Powers of Attorney",
"Immobilien und größere Vermögenswerte": "Real estate and major assets",
"kurz, für den Geschäftswert": "briefly, for the transaction value",
# Ehevertrag
"Partner 1": "Partner 1", "Partner 2": "Partner 2",
"Ehe und Vermögen": "Marriage and assets",
"Stand": "Status",
"Heirat geplant am": "Wedding planned on", "Bereits verheiratet seit": "Already married since",
"Datum": "Date",
"Gemeinsame Kinder, Kinder aus früheren Beziehungen": "Joint children, children from previous relationships",
"Vermögen Partner 1": "Assets of partner 1",
"Immobilien, Betrieb, Ersparnisse, Schulden, ungefähr": "real estate, business, savings, debts, approximately",
"Vermögen Partner 2": "Assets of partner 2",
"Einkommen beider, ungefähr": "Income of both, approximately",
"Ausländische Staatsangehörigkeit oder Wohnsitz": "Foreign nationality or residence",
"Güterstand": "Matrimonial property regime",
"Gütertrennung": "Separation of property", "Zugewinngemeinschaft mit Änderungen, etwa Betrieb ausnehmen": "Community of accrued gains with modifications, e.g. excluding a business", "Weiß ich nicht, bitte beraten": "I don't know, please advise",
"Nachehelicher Unterhalt": "Post-marital maintenance",
"Gesetzliche Regelung": "Statutory rules", "Verzicht": "Waiver", "Begrenzung": "Limitation", "Bitte beraten": "Please advise",
"Versorgungsausgleich": "Pension rights adjustment",
"Ausschluss": "Exclusion",
"Sonstige Wünsche": "Other wishes",
# Scheidung
"Ehegatte 1": "Spouse 1", "Ehegatte 2": "Spouse 2",
"Ehe": "Marriage",
"Heiratsdatum": "Date of marriage",
"Getrennt seit": "Separated since",
"Scheidungsverfahren": "Divorce proceedings",
"Noch nicht eingereicht": "Not yet filed", "Eingereicht": "Filed", "Anwalt beauftragt": "Lawyer instructed",
"Gemeinsame Kinder mit Geburtsdatum": "Joint children with dates of birth",
"Zu regeln": "To be settled",
"Ehewohnung": "Marital home",
"Gemeinsames Eigentum, ein Ehegatte übernimmt": "Jointly owned, one spouse takes over", "Gemeinsames Eigentum, Verkauf": "Jointly owned, to be sold", "Mietwohnung": "Rented", "Eigentum eines Ehegatten": "Owned by one spouse",
"Anschrift, Eigentümer, Wert, Darlehen": "address, owner, value, loans",
"Zugewinnausgleich": "Equalisation of accrued gains",
"Verzicht beiderseits": "Mutual waiver", "Zahlung eines Betrags": "Payment of a sum",
"Ausgleichsbetrag in Euro": "Equalisation amount in euros",
"Unterhalt Ehegatte": "Spousal maintenance",
"Betrag vereinbaren": "Agree an amount",
"Kindesunterhalt, Umgang": "Child maintenance, contact",
"Gesetzliche Durchführung": "Statutory procedure",
"Hausrat, Fahrzeuge, Konten": "Household goods, vehicles, accounts",
# GmbH
"Gesellschaft": "Company",
"Gewünschter Firmenname": "Desired company name",
"mit Rechtsformzusatz, gern zwei Alternativen": "with legal form suffix; two alternatives welcome",
"Sitz (Gemeinde)": "Registered seat (municipality)",
"Geschäftsanschrift": "Business address",
"Unternehmensgegenstand": "Business purpose",
"was die Gesellschaft tut, ein bis zwei Sätze": "what the company does, one or two sentences",
"Stammkapital in Euro": "Share capital in euros",
"GmbH mindestens 25.000, UG ab 1": "GmbH at least 25,000; UG from 1",
"Grundlage": "Basis",
"Musterprotokoll (bis 3 Gesellschafter, 1 Geschäftsführer)": "Model protocol (up to 3 shareholders, 1 managing director)", "Eigener Gesellschaftsvertrag": "Individual articles of association", "Weiß ich noch nicht": "Not sure yet",
"Geschäftsjahr": "Financial year",
"Kalenderjahr": "Calendar year", "Abweichend": "Other",
"Beurkundung": "Notarisation",
"In der Kanzlei": "At the office", "Online per Video, falls möglich": "Online by video, if possible",
"Gesellschafter 1": "Shareholder 1",
"Anteil am Stammkapital in Euro": "Share of capital in euros",
"Auch Geschäftsführer?": "Also managing director?",
"Gesellschafter 2": "Shareholder 2",
"Falls vorhanden. Weitere unter Besonderheiten.": "If any. Additional shareholders under Remarks.",
"Geschäftsführung": "Management",
"Geschäftsführer, falls nicht Gesellschafter": "Managing director, if not a shareholder",
"Name, Geburtsdatum, Anschrift": "name, date of birth, address",
"Vertretung": "Representation",
"Einzelvertretung": "Sole representation", "Gemeinsam mit einem weiteren Geschäftsführer": "Jointly with another managing director",
"Befreiung von § 181 BGB": "Exemption from section 181 German Civil Code",
"Geschäfte mit sich selbst": "self-dealing",
"Wirtschaftlich Berechtigte": "Beneficial owners",
"natürliche Personen mit mehr als 25 % Anteil oder Kontrolle": "natural persons with more than 25 % or control",
# Anteile
"Firma": "Company name",
"Handelsregister, HRB-Nummer": "Commercial register, HRB number",
"Sitz": "Registered seat",
"Aktuelle Gesellschafterliste vorhanden?": "Current list of shareholders available?",
"Ja, bringe ich mit": "Yes, I will bring it", "Bitte vom Register abrufen": "Please retrieve from the register",
"Veräußerer": "Transferor (seller)",
"Erwerber": "Acquirer (buyer)",
"Wirtschaftlich Berechtigte des Erwerbers, falls Gesellschaft": "Beneficial owners of the acquirer, if a company",
"Anteile und Gegenleistung": "Shares and consideration",
"Übertragene Anteile": "Shares transferred",
"laufende Nummern und Nennbeträge laut Gesellschafterliste": "serial numbers and nominal amounts per list of shareholders",
"Verkauf": "Sale", "Schenkung": "Gift", "Einbringung": "Contribution",
"Wirtschaftlicher Übergang": "Economic transfer date",
"Änderung der Geschäftsführung?": "Change of management?",
"Ja, bitte erklären": "Yes, please explain",
"Zustimmung der Gesellschaft erforderlich?": "Company consent required?",
# Handelsregister
"Registergericht und Nummer": "Register court and number",
"z. B. AG Freiburg HRB 12345": "e.g. Freiburg Local Court HRB 12345",
"Rechtsform": "Legal form",
"GmbH": "GmbH", "UG (haftungsbeschränkt)": "UG (haftungsbeschränkt)", "Einzelkaufmann": "Sole trader", "OHG": "OHG (general partnership)", "KG": "KG (limited partnership)", "GmbH & Co. KG": "GmbH & Co. KG",
"Anmeldung": "Filing",
"Was soll angemeldet werden?": "What is to be filed?",
"Geschäftsführerwechsel": "Change of managing director", "Änderung der Vertretungsbefugnis": "Change of representation rules", "Sitzverlegung": "Relocation of seat", "Änderung der Geschäftsanschrift": "Change of business address", "Satzungsänderung": "Amendment of articles", "Kapitalerhöhung": "Capital increase", "Prokura": "Prokura (commercial power of attorney)", "Auflösung, Liquidation": "Dissolution, liquidation", "Ersteintragung Einzelkaufmann oder Personengesellschaft": "First registration of sole trader or partnership",
"Einzelheiten": "Details",
"Wer scheidet aus, wer kommt hinzu, neue Anschrift, neuer Wortlaut": "who leaves, who joins, new address, new wording",
"Gesellschafterbeschluss vorhanden?": "Shareholder resolution available?",
"Nein, bitte entwerfen": "No, please draft",
"Anmeldende Person": "Person filing",
"Geschäftsführer, Inhaber oder Gesellschafter, der unterschreibt.": "Managing director, owner or partner who signs.",
# Verein
"Verein": "Association",
"Name des Vereins": "Name of the association",
"Vereinsregister-Nummer, falls eingetragen": "Register number, if registered",
"Neugründung": "New formation", "Vorstandswechsel": "Change of board",
"Vereinszweck": "Purpose of the association",
"Datum der Gründungs- oder Mitgliederversammlung": "Date of founding or general meeting",
"Protokoll und Satzung vorhanden?": "Minutes and statutes available?",
"Nein, bitte beraten": "No, please advise",
"Vorstand": "Board",
"Vorstandsmitglieder nach § 26 BGB": "Board members under section 26 German Civil Code",
"Name, Geburtsdatum, Anschrift, Amt": "name, date of birth, address, office",
"Vertretungsregelung laut Satzung": "Representation rules per statutes",
# Beglaubigung
"Person, die unterschreibt": "Person signing",
"Dokument": "Document",
"Unterschrift unter Vollmacht": "Signature on a power of attorney", "Unterschrift unter Handelsregisteranmeldung": "Signature on a commercial register filing", "Unterschrift unter Grundbucherklärung": "Signature on a land register declaration", "Beglaubigte Kopie": "Certified copy",
"Verwendung im Land": "Country of use",
"Deutschland, Schweiz, anderes": "Germany, Switzerland, other",
"Apostille nötig?": "Apostille required?",
"Sprache des Dokuments": "Language of the document",
"Deutsch, andere": "German, other",
"Anzahl Dokumente oder Seiten": "Number of documents or pages",
"Gewünschter Zeitpunkt": "Preferred time",
}

# Oberfläche (Kopf, Fuß, Formularrahmen, Vorschau)
UI = {
"Termin anfragen": "Request an appointment",
"Zum Inhalt springen": "Skip to content",
"Hauptnavigation": "Main navigation",
"Mo–Do 8–12 und 13–17 Uhr · Fr 8–12 Uhr": "Mon–Thu 8–12 and 1–5 pm · Fri 8–12",
"Öffnungszeiten": "Office hours",
"Montag bis Donnerstag": "Monday to Thursday",
"8–12 Uhr und 13–17 Uhr": "8–12 am and 1–5 pm",
"Freitag": "Friday",
"8–12 Uhr": "8–12 am",
"Termine nach Vereinbarung.": "Appointments by arrangement.",
"Seiten": "Pages",
"Rechtliches": "Legal",
"Impressum": "Legal notice",
"Datenschutz": "Privacy",
"Offene Stellen": "Vacancies",
"Notarkammer Baden-Württemberg": "Chamber of Notaries Baden-Württemberg",
"Bundesnotarkammer": "Federal Chamber of Notaries",
"Der Notar übt ein öffentliches Amt aus. Er ist zur Unparteilichkeit und Verschwiegenheit verpflichtet. Die Gebühren sind gesetzlich festgelegt (GNotKG). Diese Seite setzt keine Cookies und bindet keine Dienste Dritter ein.": "The notary holds a public office and is bound to impartiality and confidentiality. Fees are fixed by law (GNotKG). This site sets no cookies and embeds no third-party services.",
"Landeswappen Baden-Württemberg": "Coat of arms of Baden-Württemberg",
"Fragebögen": "Questionnaires",
"Fragebogen": "Questionnaire",
"Ablauf & Unterlagen": "Procedure & Documents",
"Leistungen": "Services",
"Kosten": "Fees",
"Kanzlei": "Office",
"Kontakt": "Contact",
"Kontaktanfrage": "Contact enquiry",
"Ihre Anfrage": "Your enquiry",
"Anliegen": "Matter",
"Kurze Beschreibung": "Brief description",
"keine vertraulichen Details, die besprechen wir im Gespräch": "no confidential details; we discuss those in person",
"Immobilie kaufen oder verkaufen": "Buying or selling property", "Testament oder Erbvertrag": "Will or inheritance contract", "Erbschein, Nachlass": "Certificate of inheritance, estate", "Schenkung, Übergabe": "Gift, transfer", "Vorsorgevollmacht, Patientenverfügung": "Power of attorney, living will", "Ehevertrag, Scheidungsfolgen": "Marriage contract, divorce settlement", "GmbH, Handelsregister": "GmbH, commercial register",
"Rufen Sie an oder schreiben Sie uns. Das Büro meldet sich, klärt das Anliegen und schlägt einen Termin vor.": "Call or write to us. The office will get back to you, clarify the matter and propose an appointment.",
"Anfrage senden": "Send enquiry",
"Ich habe die": "I have read the", "gelesen. Meine Angaben werden nur zur Bearbeitung der Anfrage verwendet.": ". My details are used only to handle this enquiry.",
"Start": "Home",
"Glossar": "Glossary",
"Bad Säckingen": "Bad Säckingen",
"Fragebogen öffnen": "Open questionnaire",
"Fragebögen zur Terminvorbereitung": "Questionnaires to prepare your appointment",
"Sie tragen die Eckdaten ein, das Notariat erstellt den Entwurf. Ausfüllen am Bildschirm oder ausdrucken. Ihre Angaben werden verschlüsselt an das Notariat übermittelt und dort gespeichert, ohne Dienst eines Drittanbieters. Einen Termin vereinbaren Sie telefonisch.": "You enter the key facts, the notary's office prepares the draft. Complete on screen or print. Your details are transmitted to and stored at the notary's office in encrypted form, without any third-party service. Appointments are made by telephone.",
"An das Notariat senden": "Send to the notary's office",
"Ausdrucken und mitbringen": "Print and bring along",
"Pflichtfeld": "Required field",
"Musterseite: Der Versand ist in der Vorschau nicht angebunden.": "Sample site: sending is not connected in this preview.",
"Ihre Angaben werden verschlüsselt übertragen und verschlüsselt gespeichert. Nur das Notariat kann sie lesen. Das Notariat erhält eine Nachricht, dass ein Fragebogen eingegangen ist, ohne Ihre Daten.": "Your details are transmitted and stored in encrypted form. Only the notary's office can read them. The office is notified that a questionnaire has arrived, without your data.",
"Die Angaben dienen der Vorbereitung eines Entwurfs und werden nur dafür verwendet.": "The details serve to prepare a draft and are used for that purpose only.",
"Datenschutzhinweise": "Privacy notice",
"So geht es weiter": "What happens next",
"Sie füllen aus, was Sie wissen. Lücken sind in Ordnung.": "Fill in what you know. Gaps are fine.",
"Das Büro prüft die Angaben und ruft bei Unklarheiten zurück.": "The office checks the details and calls you if anything is unclear.",
"Sie erhalten den Entwurf zum Lesen, dann wird ein Termin vereinbart.": "You receive the draft to read, then an appointment is arranged.",
"Wichtig": "Important",
"Die Angaben werden im Entwurf verwendet. Bitte prüfen Sie Namen, Geburtsdaten und Beträge.": "The details are used in the draft. Please check names, dates of birth and amounts.",
"Bringen Sie zum Termin die": "Please bring the",
"Unterlagen aus der Checkliste": "documents from the checklist",
"mit.": "to the appointment.",
"Musterseite, nicht die Originalseite von notar-stadler.de.": "Sample site, not the original notar-stadler.de website.",
"Entwurf eines neuen Auftritts. Farbig markierte Angaben werden vor Veröffentlichung ersetzt.": "Draft of a new website. Highlighted items will be replaced before publication.",
"Handy-Ansicht": "Phone view",
"Bildschirm-Ansicht": "Desktop view",
"Alle Fragebögen": "All questionnaires",
"Zur Startseite": "Back to home",
}
